const admin = {
  admin: {
    SHOW_CREATE_DEPARTMENTS_DIALOG: "SHOW_CREATE_DEPARTMENTS_DIALOG",
    ADD_NEW_DEPARTMENT: "ADD_NEW_DEPARTMENT",
    DEFINE_OPERATION_TYPE: "DEFINE_OPERATION_TYPE",
    SELECT_ITEM_TO_MODIFY: "SELECT_ITEM_TO_MODIFY",
    EDIT_DEPARTMENT: "EDIT_DEPARTMENT",
    DELETE_DEPARTMENT: "DELETE_DEPARTMENT",

    CHANGE_DEPARTMENT_CREATED: "CHANGE_DEPARTMENT_CREATED",
    CHANGE_DEPARTMENT_EDITED: "CHANGE_DEPARTMENT_EDITED",
    CHANGE_DEPARTMENT_DELETED: "CHANGE_DEPARTMENT_DELETED",
  }
};

export default admin;
