const admin = {
  admin: {
    SHOW_CREATE_DEPARTMENTS_DIALOG: "SHOW_CREATE_DEPARTMENTS_DIALOG",
    ADD_NEW_DEPARTMENT: "ADD_NEW_DEPARTMENT",
    CHANGE_DEPARTMENT_CREATED: "CHANGE_DEPARTMENT_CREATED",
  }
};

export default admin;
