const admin = {
  admin: {
    SHOW_CREATE_DEPARTMENTS_DIALOG: "SHOW_CREATE_DEPARTMENTS_DIALOG",
    SHOW_CREATE_EMPLOYEES_DIALOG: "SHOW_CREATE_EMPLOYEES_DIALOG",

    CHANGE_CREATED: "CHANGE_CREATED",
    CHANGE_EDITED: "CHANGE_EDITED",
    CHANGE_DELETED: "CHANGE_DELETED",

    DEFINE_OPERATION_TYPE: "DEFINE_OPERATION_TYPE",
    SELECT_ITEM_TO_MODIFY: "SELECT_ITEM_TO_MODIFY",

    ADD_NEW_DEPARTMENT: "ADD_NEW_DEPARTMENT",
    EDIT_DEPARTMENT: "EDIT_DEPARTMENT",
    DELETE_DEPARTMENT: "DELETE_DEPARTMENT",

    ADD_NEW_EMPLOYEE: "ADD_NEW_EMPLOYEE",
    EDIT_EMPLOYEE: "EDIT_EMPLOYEE",
    DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  }
};

export default admin;
