const history = {
  history: {
    GET_ALL_HISTORY: "GET_ALL_HISTORY",
    UPDATE_FROM_DATE: "UPDATE_FROM_DATE",
    UPDATE_TO_DATE: "UPDATE_TO_DATE",

    UPDATE_TABLE_REQUEST: "UPDATE_TABLE_REQUEST",
    UPDATE_TABLE_SUCCESS: "UPDATE_TABLE_SUCCESS",
    UPDATE_TABLE_FAILURE: "UPDATE_TABLE_FAILURE",

    CHANGE_NEW_DELIVERY: "CHANGE_NEW_DELIVERY",
  }
};

export default history;
