const info = {
  info: {
    UPDATE_BATTERY_REQUEST: "UPDATE_BATTERY_REQUEST",
    UPDATE_BATTERY_SUCCESS: "UPDATE_BATTERY_SUCCESS",
    UPDATE_BATTERY_FAILURE: "UPDATE_BATTERY_FAILURE",

    GET_CURRENT_DELIVERY_REQUEST: "GET_CURRENT_DELIVERY_REQUEST",
    GET_CURRENT_DELIVERY_SUCCESS: "GET_CURRENT_DELIVERY_SUCCESS",
    GET_CURRENT_DELIVERY_FAILURE: "GET_CURRENT_DELIVERY_FAILURE",
  }
};

export default info;
