const receive = {
  receive: {
    SHOW_ALERT_DIALOG: "SHOW_ALERT_DIALOG",
    CHECK_ITEM: "CHECK_ITEM",
    GET_NOT_CHECKED_LIST: "GET_NOT_CHECKED_LIST",
    CHANGE_CHECKED: "CHANGE_CHECKED",
    SEND_CAR: "SEND_CAR",
    SELECT_ALL_ITEMS: "SELECT_ALL_ITEMS",

    GET_DELIVERIES_REQUEST: "GET_DELIVERIES_REQUEST",
    GET_DELIVERIES_SUCCESS: "GET_DELIVERIES_SUCCESS",
    GET_DELIVERIES_FAILURE: "GET_DELIVERIES_FAILURE",

    ALLOW_RECEIVE: "ALLOW_RECEIVE",
  }
};

export default receive;
