const request = {
  request: {
    REQUEST_CAR: "REQUEST_CAR",
    SELECT_ORIGIN_LOCATION: "SELECT_ORIGIN_LOCATION",
    SELECT_DESTINATION_LOCATION: "SELECT_DESTINATION_LOCATION",
    SELECT_RECIPIENT: "SELECT_RECIPIENT",

    ADD_LOAD_ITEM: "ADD_LOAD_ITEM",

    GET_ALL_ITEMS_REQUEST: "GET_ALL_ITEMS_REQUEST",
    GET_ALL_ITEMS_SUCCESS: "GET_ALL_ITEMS_SUCCESS",
    GET_ALL_ITEMS_FAILURE: "GET_ALL_ITEMS_FAILURE",

    DELETE_LOAD_ITEM: "DELETE_LOAD_ITEM",

    CHANGE_DELETED_VALUE: "CHANGE_DELETED_VALUE",

    SHOW_DIALOG_KEY: "SHOW_DIALOG_KEY",
    GENERATE_KEY: "GENERATE_KEY",
    DISABLE_REQUEST_BUTTON: "DISABLE_REQUEST_BUTTON",

    CREATE_DELIVERY_REQUEST: "CREATE_DELIVERY_REQUEST",
    CREATE_DELIVERY_SUCCESS: "CREATE_DELIVERY_SUCCESS",
    CREATE_DELIVERY_FAILURE: "CREATE_DELIVERY_FAILURE",
  }
};

export default request;
