const request = {
  request: {
    REQUEST_CAR: "REQUEST_CAR",
    SELECT_ORIGIN_LOCATION: "SELECT_ORIGIN_LOCATION",
    SELECT_DESTINATION_LOCATION: "SELECT_DESTINATION_LOCATION",
    ADD_LOAD_ITEM: "ADD_LOAD_ITEM",
    SHOW_DIALOG_KEY: "SHOW_DIALOG_KEY",
    GENERATE_KEY: "GENERATE_KEY",
  }
};

export default request;
